"""ajout_colonne_note

Revision ID: a5fda5d410c2
Revises: 2ca916948bbd
Create Date: 2026-06-14 15:02:44.343627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5fda5d410c2'
down_revision = '2ca916948bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medecin', schema=None) as batch_op:
        batch_op.alter_column('telephone',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_medecin_specialite', 'specialite', ['specialite_id'], ['id'])
        batch_op.create_foreign_key('fk_medecin_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_patient_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('rendez_vous', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_rdv_patient', 'patient', ['patient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rendez_vous', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rdv_patient', type_='foreignkey')
        batch_op.drop_column('note')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint('fk_patient_user', type_='foreignkey')

    with op.batch_alter_table('medecin', schema=None) as batch_op:
        batch_op.drop_constraint('fk_medecin_user', type_='foreignkey')
        batch_op.drop_constraint('fk_medecin_specialite', type_='foreignkey')
        batch_op.alter_column('telephone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###
